server:
  port: 8081

spring:
  application:
    name: prasad-blog-application
  datasource:
    url: jdbc:mysql://localhost:3306/prasad_todo_db
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true